In [2]:
import numpy as np

In [3]:
# Sigmoid Function(Activation function)
def sigmoid (x):
    
    return 1 / (1 + np.exp(-x))

In [4]:
# Derivative of Sigmoid Function(for back-propogation)
def derivatives_sigmoid(x):
    
    return x * (1 - x)

In [5]:
def nn_forward_pass(w_ih, b_ih, w_ho, b_ho):
    
    hidden_layer1_input = np.dot(X, w_ih) + b_ih
    
    hidden_layer1_output = sigmoid(hidden_layer1_input)
    
    output_layer_input = np.dot(hidden_layer1_output, w_ho) + b_ho
    
    output = sigmoid(output_layer_input)
    
    return output, hidden_layer1_output

In [6]:
def nn_back_prop(w_ih, b_ih, w_ho, b_ho, output):
    
    E = y - output
    
    slope_output_layer = derivatives_sigmoid(output)
    
    slope_hidden_layer = derivatives_sigmoid(hidden_layer1_output)
    
    d_output = E * slope_output_layer
    
    Error_at_hidden_layer = d_output.dot(w_ho.T)
    
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    
    w_ho += hidden_layer1_output.T.dot(d_output) * lr
    
    b_ho += np.sum(d_output, axis=0, keepdims=True) * lr
    
    w_ih += X.T.dot(d_hiddenlayer) * lr
    
    b_ih += np.sum(d_hiddenlayer, axis=0, keepdims=True) * lr
    
    return w_ih, b_ih, w_ho, b_ho

In [7]:
def run_network():
    
    # Input array
    X = np.array([[1,0,50,1],[1,0,75,0],[0,1,20,1]])
    
    print("Input data is :\n{}".format(X))
    
    print("\nDimensions of the input data : {}\n".format(X.shape))
    
    # Output array
    y = np.array([[1],[1],[0]])
    
    print("Output label is :\n{}".format(y))
    
    print("\nDimensions of the Output data : {}\n".format(X.shape))
    
    # Variable initialization and setting outer design of Neural network 

    epoch = 10000  # Setting training iterations

    lr = 0.05  # Setting learning rate

    inputlayer_neurons = X.shape[1]  # number of features in data set

    hiddenlayer_neurons = 3  # number of hidden layers neurons

    output_neurons = 1  # number of neurons at output layer
    
    #weight and bias initialization
    w_ih = np.random.uniform(size = (inputlayer_neurons, hiddenlayer_neurons))
    print("Initial weight matrix between input and hidden layer :\n{}".format(w_ih))

    b_ih = np.random.uniform(size = (1, hiddenlayer_neurons))
    print("\nInitial bias matrix between input and hidden layer :\n{}".format(b_ih))

    w_ho = np.random.uniform(size = (hiddenlayer_neurons, output_neurons))
    print("\nInitial weight matrix between hidden and output layer :\n{}".format(w_ho))

    b_ho = np.random.uniform(size = (1, output_neurons))
    print("\nInitial bias matrix between hidden and output layer :\n{}".format(b_ho))
    
    for i in range(epoch):
    
        output, hidden_layer1_output = nn_forward_pass(w_ih, b_ih, w_ho, b_ho)
    
        w_ih, b_ih, w_ho, b_ho = nn_back_prop(w_ih, b_ih, w_ho, b_ho, output)
    
    print("\nPrediction from neural network :\n{}".format(output))

In [8]:
run_network()

Input data is :
[[ 1  0 50  1]
 [ 1  0 75  0]
 [ 0  1 20  1]]

Dimensions of the input data : (3, 4)

Output label is :
[[1]
 [1]
 [0]]

Dimensions of the Output data : (3, 4)

Initial weight matrix between input and hidden layer :
[[0.87934618 0.91024629 0.23607113]
 [0.91094895 0.67371226 0.32043583]
 [0.24809409 0.94205997 0.76920628]
 [0.16469855 0.24850237 0.59037689]]

Initial bias matrix between input and hidden layer :
[[0.84098043 0.96321815 0.97138594]]

Initial weight matrix between hidden and output layer :
[[0.3718534 ]
 [0.74299396]
 [0.15421842]]

Initial bias matrix between hidden and output layer :
[[0.15998669]]


NameError: name 'X' is not defined